import { ArrowRight, Bus, Clock3, MapPin, Navigation, Phone, ShieldCheck, Star, Store } from "lucide-react";

export default function VisitPage() {
  return (
    <div className="visit-page">
      <header className="page-hero visit-hero"><div className="container-wide"><div><span className="eyebrow eyebrow-light">Visit Royco</span><h1>Come closer to<br /><em>the details.</em></h1><p>Try pieces, compare weights and finishes, and choose at your own pace with our Chandannagar team.</p><div className="visit-hero-actions"><a className="button button-gold" href="https://maps.google.com/?cid=12735356697874811323" target="_blank" rel="noreferrer">Get directions <Navigation /></a><a className="button button-ghost-light" href="tel:+913326835943">Call the showroom</a></div></div><div className="visit-rating-card"><div><strong>4.2</strong><span>★★★★★</span></div><p>Based on 89 Google reviews</p><small>Jewelry store · Delivery available</small></div></div></header>
      <section className="visit-details container-wide"><div className="visit-map-large"><div className="map-grid map-grid-large" aria-hidden="true"><i /><i /><i /><i /><i /><i /><b /></div><span className="map-pin map-pin-large"><MapPin fill="currentColor" /></span><div className="map-label map-label-large"><strong>Royco Jewellers</strong><small>22.8637568, 88.366625</small></div><a className="map-open" href="https://www.google.com/maps/search/?api=1&query=22.8637568%2C88.366625" target="_blank" rel="noreferrer">Open in Google Maps <ArrowRight /></a></div><div className="visit-info"><span className="eyebrow">Store information</span><h2>Royco Jewellers<br /><em>রায়কো জুয়েলার্স</em></h2><div className="info-list"><div><MapPin /><span><small>Address</small><strong>Bagbazar Plaza, Rash Behari Avenue, Bagbazar, Sukhsanatantala, Chandannagar, West Bengal 712136</strong></span></div><div><Clock3 /><span><small>Opening hours</small><strong>10:30 am — 9:00 pm</strong><b>Open daily · Please call on public holidays</b></span></div><div><Phone /><span><small>Telephone</small><a href="tel:+913326835943">033 2683 5943</a></span></div><div><Store /><span><small>Store code</small><strong>V978+GJ Chandannagar, West Bengal</strong></span></div></div></div></section>
      <section className="visit-planning"><div className="container-wide"><div className="planning-heading"><span className="eyebrow eyebrow-light">Before you arrive</span><h2>A little planning,<br /><em>a better visit.</em></h2></div><div className="planning-grid"><div><span>01</span><Bus /><h3>Getting here</h3><p>Bagbazar Plaza on Rash Behari Avenue. Use the direction link for live traffic and transit guidance.</p></div><div><span>02</span><Clock3 /><h3>Best time</h3><p>Late mornings and early afternoons are generally quieter for unhurried consultations.</p></div><div><span>03</span><ShieldCheck /><h3>For a specific piece</h3><p>Call ahead with the product name or SKU and our team can confirm showroom availability.</p></div></div></div></section>
      <section className="visit-review container"><Star fill="currentColor" /><blockquote>“Very satisfied with their collection and price. Thank you.”</blockquote><p>Recent Royco visitor</p></section>
    </div>
  );
}
