CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  email_normalized TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  phone TEXT,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  bengali_name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  material TEXT NOT NULL CHECK (material IN ('Gold', 'Silver', 'Platinum', 'Diamond')),
  category TEXT NOT NULL CHECK (category IN ('Rings', 'Earrings', 'Necklaces', 'Bangles', 'Chains', 'Pendants', 'Bracelets', 'Mangalsutra')),
  purity TEXT NOT NULL DEFAULT '',
  weight_grams NUMERIC(10, 3) NOT NULL DEFAULT 0 CHECK (weight_grams >= 0),
  price_paise BIGINT NOT NULL CHECK (price_paise >= 0),
  compare_at_price_paise BIGINT CHECK (compare_at_price_paise IS NULL OR compare_at_price_paise >= price_paise),
  stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  image_url TEXT NOT NULL DEFAULT '',
  gallery JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(gallery) = 'array'),
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS promotions (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  discount_type TEXT NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
  discount_value BIGINT NOT NULL CHECK (discount_value > 0),
  min_order_paise BIGINT NOT NULL DEFAULT 0 CHECK (min_order_paise >= 0),
  max_discount_paise BIGINT CHECK (max_discount_paise IS NULL OR max_discount_paise > 0),
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at),
  CHECK (discount_type <> 'percent' OR discount_value <= 100)
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  order_number TEXT NOT NULL UNIQUE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')),
  subtotal_paise BIGINT NOT NULL CHECK (subtotal_paise >= 0),
  discount_paise BIGINT NOT NULL DEFAULT 0 CHECK (discount_paise >= 0),
  shipping_paise BIGINT NOT NULL DEFAULT 0 CHECK (shipping_paise >= 0),
  total_paise BIGINT NOT NULL CHECK (total_paise >= 0),
  promo_code TEXT,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  shipping_address JSONB NOT NULL CHECK (jsonb_typeof(shipping_address) = 'object'),
  payment_method TEXT NOT NULL DEFAULT 'cod' CHECK (payment_method IN ('cod', 'store', 'bank_transfer')),
  notes TEXT NOT NULL DEFAULT '',
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  sku TEXT NOT NULL,
  name TEXT NOT NULL,
  material TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL DEFAULT '',
  unit_price_paise BIGINT NOT NULL CHECK (unit_price_paise >= 0),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  line_total_paise BIGINT NOT NULL CHECK (line_total_paise >= 0)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  actor_role TEXT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB CHECK (jsonb_typeof(metadata) = 'object'),
  ip_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE products ADD COLUMN IF NOT EXISTS bengali_name TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS products_catalogue_idx ON products (active, material, category, featured);
CREATE INDEX IF NOT EXISTS products_search_idx ON products USING GIN (to_tsvector('english', name || ' ' || description || ' ' || material || ' ' || category));
CREATE INDEX IF NOT EXISTS orders_user_created_idx ON orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS orders_status_created_idx ON orders (status, created_at DESC);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items (order_id);
CREATE INDEX IF NOT EXISTS sessions_user_active_idx ON sessions (user_id, expires_at) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS audit_created_idx ON audit_logs (created_at DESC);

INSERT INTO products
  (sku, slug, name, description, material, category, purity, weight_grams, price_paise, compare_at_price_paise, stock, image_url, featured)
VALUES
  ('RJ-GR-001', 'sunlit-lotus-gold-ring', 'Sunlit Lotus Gold Ring', 'A sculpted lotus ring with a warm high-polish finish, made for everyday celebrations.', 'Gold', 'Rings', '22K', 5.200, 4620000, 4890000, 8, '/assets/products/gold-ring.webp', TRUE),
  ('RJ-GE-001', 'nakshi-drop-gold-earrings', 'Nakshi Drop Gold Earrings', 'Bengal-inspired nakshi drops with delicate beadwork and a secure screw back.', 'Gold', 'Earrings', '22K', 7.800, 6880000, 7250000, 6, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-GN-001', 'royal-bagbazar-gold-necklace', 'Royal Bagbazar Gold Necklace', 'A statement necklace with layered floral links inspired by Chandannagar heritage.', 'Gold', 'Necklaces', '22K', 28.500, 24950000, 25900000, 3, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-GB-001', 'heritage-ribbed-gold-bangles', 'Heritage Ribbed Gold Bangles', 'A matched pair of timeless ribbed bangles with hand-finished edges.', 'Gold', 'Bangles', '22K', 21.400, 18750000, 19400000, 4, 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-GC-001', 'classic-rope-gold-chain', 'Classic Rope Gold Chain', 'A flexible rope-link chain that catches the light from every angle.', 'Gold', 'Chains', '22K', 11.750, 10250000, 10800000, 7, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-GP-001', 'shakti-gold-pendant', 'Shakti Gold Pendant', 'An intricate temple-inspired pendant with a refined antique-gold finish.', 'Gold', 'Pendants', '22K', 4.300, 3820000, 4050000, 10, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-GBR-001', 'woven-glow-gold-bracelet', 'Woven Glow Gold Bracelet', 'Soft woven links meet a polished clasp in this lightweight gold bracelet.', 'Gold', 'Bracelets', '18K', 8.900, 6120000, 6450000, 5, 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-GM-001', 'ananya-gold-mangalsutra', 'Ananya Gold Mangalsutra', 'A contemporary black-bead mangalsutra with a graceful twin-drop centerpiece.', 'Gold', 'Mangalsutra', '22K', 10.600, 9280000, 9750000, 5, 'https://images.unsplash.com/photo-1599459183200-59c7687a0275?auto=format&fit=crop&w=1200&q=85', TRUE),

  ('RJ-SR-001', 'moonwater-silver-ring', 'Moonwater Silver Ring', 'A fluid open ring in rhodium-finished sterling silver.', 'Silver', 'Rings', '925', 4.100, 385000, 425000, 18, 'https://images.unsplash.com/photo-1603561596112-db1d0d140b8c?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-SE-001', 'shiuli-silver-earrings', 'Shiuli Silver Earrings', 'Petite shiuli-flower studs with oxidised detailing.', 'Silver', 'Earrings', '925', 5.500, 465000, 520000, 15, 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-SN-001', 'chandannagar-filigree-necklace', 'Chandannagar Filigree Necklace', 'Airy sterling-silver filigree in a comfortable collar silhouette.', 'Silver', 'Necklaces', '925', 31.000, 1285000, 1425000, 8, 'https://images.unsplash.com/photo-1619119069152-a2b331eb392a?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-SB-001', 'ghat-etched-silver-bangle', 'Ghat Etched Silver Bangle', 'Architectural etching and a hidden clasp give this bangle a clean profile.', 'Silver', 'Bangles', '925', 22.800, 985000, 1090000, 9, 'https://images.unsplash.com/photo-1576022167564-3e7ad4c70e55?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-SC-001', 'everyday-box-silver-chain', 'Everyday Box Silver Chain', 'A strong, understated box chain finished for lasting brightness.', 'Silver', 'Chains', '925', 8.200, 445000, NULL, 22, 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-SP-001', 'river-pearl-silver-pendant', 'River Pearl Silver Pendant', 'A luminous freshwater pearl suspended from a polished silver arc.', 'Silver', 'Pendants', '925', 3.900, 525000, 590000, 16, 'https://images.unsplash.com/photo-1590166223826-12dee1677420?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-SBR-001', 'oxidised-charms-silver-bracelet', 'Oxidised Charms Silver Bracelet', 'Tiny heritage motifs create a playful oxidised-silver charm bracelet.', 'Silver', 'Bracelets', '925', 12.400, 675000, 750000, 11, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-SM-001', 'tara-silver-mangalsutra', 'Tara Silver Mangalsutra', 'Sterling silver, black beads and a minimal star motif for modern daily wear.', 'Silver', 'Mangalsutra', '925', 7.600, 615000, 690000, 12, 'https://images.unsplash.com/photo-1603974372039-adc49044b6bd?auto=format&fit=crop&w=1200&q=85', FALSE),

  ('RJ-PR-001', 'infinity-platinum-ring', 'Infinity Platinum Ring', 'A smooth infinity profile cast in naturally white platinum.', 'Platinum', 'Rings', 'PT950', 6.100, 8950000, 9450000, 7, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-PE-001', 'orbit-platinum-earrings', 'Orbit Platinum Earrings', 'Interlocking orbital hoops in bright PT950 platinum.', 'Platinum', 'Earrings', 'PT950', 8.600, 12250000, 12900000, 5, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-PN-001', 'celestial-platinum-necklace', 'Celestial Platinum Necklace', 'A precise line of platinum links with a sculptural central sweep.', 'Platinum', 'Necklaces', 'PT950', 24.200, 32800000, 34200000, 2, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-PB-001', 'parallel-platinum-bangle', 'Parallel Platinum Bangle', 'Twin parallel ridges give this platinum bangle quiet dimension.', 'Platinum', 'Bangles', 'PT950', 18.900, 25750000, 26900000, 3, 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-PC-001', 'anchor-platinum-chain', 'Anchor Platinum Chain', 'A substantial anchor-link chain with a seamless lobster clasp.', 'Platinum', 'Chains', 'PT950', 14.500, 19850000, 20800000, 4, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-PP-001', 'north-star-platinum-pendant', 'North Star Platinum Pendant', 'A crisp eight-point star pendant in satin and polished platinum.', 'Platinum', 'Pendants', 'PT950', 5.100, 7420000, 7950000, 8, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-PBR-001', 'continuum-platinum-bracelet', 'Continuum Platinum Bracelet', 'Rounded platinum links engineered for supple movement and durability.', 'Platinum', 'Bracelets', 'PT950', 12.750, 17400000, 18200000, 4, 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-PM-001', 'everbond-platinum-mangalsutra', 'Everbond Platinum Mangalsutra', 'Rare platinum and black onyx beads in a subtle forever-knot design.', 'Platinum', 'Mangalsutra', 'PT950', 9.300, 13150000, 13900000, 3, 'https://images.unsplash.com/photo-1599459183200-59c7687a0275?auto=format&fit=crop&w=1200&q=85', FALSE),

  ('RJ-DR-001', 'aurora-diamond-solitaire-ring', 'Aurora Diamond Solitaire Ring', 'A brilliant-cut certified diamond lifted in a graceful six-prong setting.', 'Diamond', 'Rings', '18K / 0.75 ct', 4.800, 18900000, 20500000, 5, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-DE-001', 'dewdrop-diamond-earrings', 'Dewdrop Diamond Earrings', 'Graduated diamond drops designed for fluid sparkle.', 'Diamond', 'Earrings', '18K / 0.62 ct', 6.200, 15650000, 16900000, 5, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-DN-001', 'rajkumari-diamond-necklace', 'Rajkumari Diamond Necklace', 'A bridal diamond necklace balancing floral clusters with fine articulation.', 'Diamond', 'Necklaces', '18K / 4.80 ct', 32.000, 78500000, 82900000, 2, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-DB-001', 'constellation-diamond-bangle', 'Constellation Diamond Bangle', 'Scattered brilliant diamonds create a modern constellation across the wrist.', 'Diamond', 'Bangles', '18K / 1.20 ct', 17.600, 29400000, 31500000, 3, 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-DC-001', 'tennis-diamond-chain', 'Tennis Diamond Chain', 'A continuous line of matched diamonds with a double-safety clasp.', 'Diamond', 'Chains', '18K / 3.10 ct', 19.200, 64200000, 67900000, 2, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-DP-001', 'flame-diamond-pendant', 'Flame Diamond Pendant', 'A pear-cut centre stone framed by a delicate diamond halo.', 'Diamond', 'Pendants', '18K / 0.55 ct', 3.900, 12850000, 13900000, 7, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1200&q=85', FALSE),
  ('RJ-DBR-001', 'starlight-diamond-bracelet', 'Starlight Diamond Bracelet', 'Flexible diamond stations give this bracelet an airy, contemporary rhythm.', 'Diamond', 'Bracelets', '18K / 1.45 ct', 11.300, 33750000, 35900000, 4, 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1200&q=85', TRUE),
  ('RJ-DM-001', 'soumyo-diamond-mangalsutra', 'Soumyo Diamond Mangalsutra', 'A geometric diamond centre meets classic black beads in a refined heirloom.', 'Diamond', 'Mangalsutra', '18K / 0.48 ct', 8.700, 11600000, 12450000, 6, 'https://images.unsplash.com/photo-1599459183200-59c7687a0275?auto=format&fit=crop&w=1200&q=85', TRUE)
ON CONFLICT (sku) DO NOTHING;

INSERT INTO promotions
  (id, code, title, description, discount_type, discount_value, min_order_paise, max_discount_paise, starts_at, ends_at, active)
VALUES
  ('promo-royco10', 'ROYCO10', 'Royco Celebration', 'Save 10% on orders of ₹25,000 or more.', 'percent', 10, 2500000, 750000, NULL, NULL, TRUE),
  ('promo-zeromaking', 'ZEROMAKING', 'Zero Making Celebration', 'A special 8% online saving inspired by Royco zero-making-charge events.', 'percent', 8, 0, 750000, NULL, NULL, TRUE),
  ('promo-bridal15', 'BRIDAL15', 'Bridal Edit', 'Save 15% on bridal orders above ₹1,50,000.', 'percent', 15, 15000000, 3000000, NULL, NULL, TRUE),
  ('promo-welcome2500', 'WELCOME2500', 'Welcome to Royco', '₹2,500 off your first online order above ₹50,000.', 'fixed', 250000, 5000000, NULL, NULL, NULL, TRUE)
ON CONFLICT (code) DO NOTHING;
